sunshine_name = fengluoxiao-Hyprland
locale = zh
address_family = ipv4
bind_address = 0.0.0.0
external_ip = 192.168.0.111
capture = wlr
encoder = vaapi
adapter_name = /dev/dri/renderD128
upnp = disabled
